DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS meals;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name             VARCHAR(255)                     NOT NULL,
    email            VARCHAR(255)                     NOT NULL,
    password         VARCHAR(255)                     NOT NULL,
    registered       TIMESTAMP          DEFAULT CURRENT_TIMESTAMP NOT NULL,
    enabled          BOOLEAN            DEFAULT TRUE  NOT NULL,
    calories_per_day INTEGER            DEFAULT 2000  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_role
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255) NOT NULL,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE meals
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    date_time   TIMESTAMP NOT NULL,
    description VARCHAR(255)   NOT NULL,
    calories    INTEGER   NOT NULL,
    user_id     INTEGER   NOT NULL,
    CONSTRAINT meals_idx UNIQUE (user_id, date_time),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

SELECT * FROM meals WHERE user_id=100000 AND (date_time>='2023-06-19 09:00:00.000000' AND date_time<'2023-06-19 23:00:00.000000');